package com.huir.GmaoApp.model;

public enum TypeRapport {
    EQUIPEMENTS, MAINTENANCE_PREVENTIVE, MAINTENANCE_CORRECTIVE, COUTS_MAINTENANCE, STOCK_PIECES, PERFORMANCE_EQUIPEMENTS, INTERVENTIONS_TECHNICIENS
}